##make the Docker Login Action available to the workflow, using the Secret "DOCKERTOKEN" as the password

name: Auth to DockerHub

on:
  push:
    branches: [ "main" ]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Authenticate to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERUSERNAME }}
            password: ${{ secrets.DOCKERTOKEN }}