name: Full Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: palserv:latest
  DOCKERFILE_PATH: src/PalworldServer.Grpc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - name: Authentification DockerHub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u ${{ secrets.DOCKERUSERNAME }} --password-stdin
      - name: Construction de l'Image Docker depuis le Dockerfile
        run: docker build -t ${{ env.IMAGE_NAME }} -f ${{ env.DOCKERFILE_PATH }}/Dockerfile ${{ env.DOCKERFILE_PATH }}
      - name: Publication de l'Image sur DockerHub
        run: docker push ${{ secrets.DOCKERUSERNAME }}/${{ env.IMAGE_NAME }}