name: Full Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  auth-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-auth.yml

  build-docker:
    runs-on: ubuntu-latest
    needs: auth-dockerhub
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-build.yml

  push-docker:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-push.yml